package:
  name: mdahole2
  version: "0.2.0"

source:
  path: .
  
requirements:
  channels:
    - conda-forge
    - defaults
  
  build:
    - python
    - setuptools

  run:
    - python
    - hole2
    - mdanalysis
