name: docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  docs:
    if: "github.repository == 'MDAnalysis/hole2-mdakit'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup_miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        environment-file: docs/requirements.yaml
        auto-update-conda: true
        channel-priority: flexible
        channels: conda-forge
        miniforge-variant: Mambaforge
        use-mamba: true

    - name: install dependencies
      run: |
        python -m pip install MDAnalysis

    - name: install package
      run: |
        python -m pip install .

    - name: build docs
      run: |
        cd docs && sphinx-build -b html source build

    - name: deploy docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name != 'pull_request'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
        user_name: 'github-actions'
        user_email: 'github-action@users.noreply.github.com'
